events { worker_connections 1024; }
http {
    server {
        listen 8080;
        location / {
            proxy_pass https://ai.len.co.id:8001;
            proxy_ssl_server_name on;
            proxy_set_header Host ai.len.co.id;
            proxy_set_header X-API-Key sk_dev_ik83Yi4SraHQZ5QXj1JdCgcqbsDmavWD;
            proxy_hide_header Authorization;
            proxy_set_header Authorization "";
        }
    }
}
